### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by aliceFrontend** [MikhailGlushko/SFDC-Contact-Manager-demo-task#1]
Здравствуйте, можно с вами связаться? Я бы хотела кое что спросить, если можно.

**Comment by MikhailGlushko** [comment]
Добрый день, 
Если что-то вспомню то отвечу, но я SFDC не занимаюсь!
Михаил.

**Comment by MikhailGlushko** [comment]
> Здравствуйте, можно с вами связаться? Я бы хотела кое что спросить, если можно.
Добрый день,
Если что-то вспомню то отвечу, но я SFDC не занимаюсь!
Михаил.

**Comment by MikhailGlushko** [comment]
Добрый день,
Если что-то вспомню то отвечу, но я SFDC не занимаюсь!
Михаил.

**Comment by aliceFrontend** [comment]
Я хотела бы спросить вас по Salesforce, тестовому заданию которое вы делали (точно такое же дали мне и я даже не знаю как оно должно выглядеть) 21:21, 1 июня 2020 г., Mikhail Glushko <notifications@github.com>:
Добрый день,
Если что-то вспомню то отвечу, но я SFDC не занимаюсь!
Михаил.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты

**Comment by MikhailGlushko** [comment]
Контора, которая давала его читала лекции (несколько вебинаров), этого было достаточно чтобы начать работу над заданием., остальное смотрел примеры на сеилфорсе, читал доку, что-то смотрел в инете, перед этим прошел пол курса у нас в городе, но так и не сложилось...
В итоге отправил им задание, сказали ждите проверку и ждите ответ, ответа так и не поступили, ни какого, ни положительного ни отрицательного.

Прошло почти два года, я к этому виду программирования больше не возвращался...
П.С. Будут вопросы по джаве - могу ответить.

**Comment by aliceFrontend** [comment]
Вы есть в телеграмме?  Там было бы удобнее общаться) 12:24, 3 июня 2020 г., Mikhail Glushko <notifications@github.com>:
Контора, которая давала его читала лекции (несколько вебинаров), этого было достаточно чтобы начать работу над заданием., остальное смотрел примеры на сеилфорсе, читал доку, что-то смотрел в инете, перед этим прошел пол курса у нас в городе, но так и не сложилось...
В итоге отправил им задание, сказали ждите проверку и ждите ответ, ответа так и не поступили, ни какого, ни положительного ни отрицательного.
Прошло почти два года, я к этому виду программирования больше не возвращался...
П.С. Будут вопросы по джаве - могу ответить.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
-- Отправлено из мобильного приложения Яндекс.Почты
